apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: cab-booking
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 3004
      targetPort: 3004
  type: ClusterIP
